/**
 * Use **double asterisks** for bold segments (rendered in About section).
 */
export const aboutParagraphs = [
  "I joined a team of eight designers working mostly in isolation. No shared system, no shared tokens. Each feature team carried its own assumptions about buttons, forms, and spacing. The first move was not picking a framework. It was an inventory: what already existed, what was silently duplicated, what got reinvented every sprint. Teams skip that step. It is the step that decides whether a system survives.",
  "From that inventory, **Aurora** grew: a token-first library informed by **IBM Carbon**, built before Figma Variables existed, using **Token Studio** at an early stage. The architecture stays three layers for authors (global, semantic, component-scoped) and flattens into predictable CSS variables for consumers. A **Python** build replaced a generic Style Dictionary setup so we control transforms when exports change. Developers see names like `--primary-hover` without hand-maintaining hover math across six theme packages.",
  "In parallel I initiated **Luminis** for more than thirty internal apps that had been shaped by whichever technical lead was in the room. Different CSS habits, different navigation models. Developers could not move cross-team; power users lost context switching products. I froze **shadcn** on **Tailwind v4**, piloted with **Wave**, turned production learnings into guidelines, then packaged **starter kits** and **Cursor** rules. The target scenario is practical: one product owner, one front-end engineer, an internal app that still matches the rest of the suite without a full-time systems designer embedded in every squad.",
  "The work is not only files in a repo. I ran designer–developer community meetings, handoff workshops, and training on **Figma** dev mode and version hygiene. Most handoff failures were communication gaps, not missing components. The system is infrastructure; the community is how it stays true after launch.",
  "I also treat the system as a product for **agents**, not only humans. I synthesized **IDS AI 2026** across fourteen sessions into a phased roadmap: **machine-readable component contracts** (props, variants, accessibility, usage in a consistent shape), **MCP-style tools** for scoped component and token retrieval, **agent guardrails** (Cursor rules, skills, and explicit anti-patterns), and a graduated trust model for what can auto-fix versus what stays suggest-only. **Code Connect** is part of that tether — today nine of **151** Aurora exports are mapped, with a deliberate backlog to close parity with the full surface area.",
  "Currently: **Design System Lead** shipping **AI-ready UI infrastructure** — tokens, pipelines, docs, and agent-consumable metadata so humans and tools pull from the same contract. Previously: **product design**, **visual design**, and **front-end** work across digital platforms and agencies.",
] as const;
